name: Set up powershell
description: Installs and caches build dependencies

inputs:
  checkout:
    description: Whether to checkout the repository
    required: false

runs:
  using: composite
  steps:
    - name: Checkout
      if: inputs.checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false

    - name: Restore dependencies
      id: restore-dependencies
      uses: actions/cache/restore@v4
      with:
        path: ~/.local/share/powershell/Modules/
        key: pwsh-module-cache
        restore-keys: pwsh-module-cache

    - name: Install dependencies
      if: ${{ steps.restore-dependencies.outputs.cache-hit != 'true' }}
      shell: pwsh
      run: ./.build.ps1 -Bootstrap

    - name: Save dependencies
      if: ${{ steps.restore-dependencies.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ~/.local/share/powershell/Modules/
        key: ${{ steps.restore-dependencies.outputs.cache-primary-key }}
