name: Publish powershell

on:
  workflow_call:
    inputs:
      event_json:
        required: true
        type: string
    secrets:
      RELEASE_BOT_GITHUB_TOKEN:
        required: true
      PSGALLERY_API_KEY:
        required: true

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  publish-powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          token: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}

      - uses: fsackur/ci/.github/actions/setup-powershell@main

      - name: Update version
        run: |
          $Labels = @'
            ${{ toJson(fromJson(inputs.event_json).pull_request.labels.*.name) }}
          '@ | ConvertFrom-Json

          $ReleaseLabel = @($Labels) -match '^release-'
          if ($ReleaseLabel.Count -gt 1)
          {
              "Multiple release labels found: $ReleaseLabel" | Write-Host -ForegroundColor Red
              exit 1
          }

          $Release = if ($ReleaseLabel) {$ReleaseLabel -replace '^release-'} else {'${{ inputs.release }}'}

          Invoke-Build UpdateVersion -Release $Release

      - name: Test
        run: |
          Invoke-Build Build, Test

      - name: Release
        env:
          GH_TOKEN: ${{ secrets.RELEASE_BOT_GITHUB_TOKEN }}
        run: |
          git config --global user.name "dusty-release-bot"
          git config --global user.email "release-bot@dustyfox.uk"

          Invoke-Build Tag, Push, Publish -PSGalleryApiKey '${{ secrets.PSGALLERY_API_KEY }}'
