name: Release powershell

on:
  workflow_call:
    inputs:
      event_json:
        required: true
        type: string
    secrets:
      DUSTY_RELEASE_BOT_PRIVATE_KEY:
        required: true
      PSGALLERY_API_KEY:
        required: true

permissions:
  contents: write

defaults:
  run:
    shell: pwsh

jobs:
  release-powershell:
    runs-on: ubuntu-latest
    steps:
      - name: Generate bot token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: 1082187
          private-key: ${{ secrets.DUSTY_RELEASE_BOT_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          token: ${{ steps.app-token.outputs.token }}

      - name: Restore dependencies
        uses: fsackur/ci/.github/actions/setup-powershell@main

      - name: Update version
        run: |
          $PrLabels = '${{ toJson(fromJson(inputs.event_json).pull_request.labels.*.name) }}' | ConvertFrom-Json
          $ManualRelease = '${{ inputs.release }}'

          $ReleaseLabel = @($PrLabels) -match '^release-'
          if ($ReleaseLabel.Count -gt 1)
          {
              "Multiple release labels found: $ReleaseLabel" | Write-Host -ForegroundColor Red
              exit 1
          }
          $Release = if ($ReleaseLabel) {$ReleaseLabel -replace '^release-'} else {$ManualRelease}

          Invoke-Build UpdateVersion -Release $Release

      - name: Test
        run: |
          Invoke-Build Build, Test

      - name: Configure git
        run: |
          $KeyFile = "$PWD/.git/dusty-release"
          $PrivateKey = '${{ secrets.DUSTY_RELEASE_BOT_PRIVATE_KEY }}'
          [IO.File]::WriteAllText($KeyFile, $PrivateKey)
          chmod 600 $KeyFile
          ssh-keygen -y -f $KeyFile > "$KeyFile.pub"
          git update-index --assume-unchanged $KeyFile "$KeyFile.pub"

          git config --global user.name dusty-release-bot
          git config --global user.email release-bot@dustyfox.uk
          git config --global user.signingKey $KeyFile
          git config --global gpg.format ssh
          git config --global commit.gpgsign true

      - name: Release
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: |
          Invoke-Build Publish -PSGalleryApiKey '${{ secrets.PSGALLERY_API_KEY }}'
