name: Test powershell

on:
  workflow_call:

defaults:
  run:
    shell: pwsh

jobs:
  test-powershell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: fsackur/ci/.github/actions/setup-powershell@main

      - name: Build
        run: Invoke-Build Build

      - name: Test
        run: Invoke-Build Test
